### ISSUE TITLE
CSS Files are not included in CDN

### ISSUE THREAD

**Issue by benediktarnold** [benediktarnold/yui3-gallery#1]
CSS Files are not included in CDN -> seems to be an build config issue

**Comment by lukecyca** [comment]
I think I have the same problem, but not with CDN.

The browser is trying to load a css file from:
`build/gallery-datatable-col-resize/assets/skins/sam/gallery-datatable-col-resize.css`
but it only exists at:
`build/gallery-datatable-col-resize/assets/gallery-datatable-col-resize-core.css`

I'm not sure how to correctly fix this.
